//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbicacionGeografica", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UbicacionGeografica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdUbicacionGeograficaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private System.Nullable<decimal> LatitudField;
        
        private System.Nullable<decimal> LongitudField;
        
        private System.Nullable<int> IdPadreField;
        
        private int IdTipoField;
        
        private int IdUsuarioRegistroField;
        
        private System.DateTime FechaRegistroField;
        
        private System.Nullable<int> IdUsuarioModificacionField;
        
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica PadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdUbicacionGeografica {
            get {
                return this.IdUbicacionGeograficaField;
            }
            set {
                if ((this.IdUbicacionGeograficaField.Equals(value) != true)) {
                    this.IdUbicacionGeograficaField = value;
                    this.RaisePropertyChanged("IdUbicacionGeografica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<decimal> Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.Nullable<decimal> Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> IdPadre {
            get {
                return this.IdPadreField;
            }
            set {
                if ((this.IdPadreField.Equals(value) != true)) {
                    this.IdPadreField = value;
                    this.RaisePropertyChanged("IdPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int IdTipo {
            get {
                return this.IdTipoField;
            }
            set {
                if ((this.IdTipoField.Equals(value) != true)) {
                    this.IdTipoField = value;
                    this.RaisePropertyChanged("IdTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica Padre {
            get {
                return this.PadreField;
            }
            set {
                if ((object.ReferenceEquals(this.PadreField, value) != true)) {
                    this.PadreField = value;
                    this.RaisePropertyChanged("Padre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UbicacionGeografica", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.UbicacionGeografica.Cont" +
        "rato")]
    [System.SerializableAttribute()]
    public partial class UbicacionGeografica1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPadreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUbicacionGeograficaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1 PadreField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo {
            get {
                return this.CodigoField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoField, value) != true)) {
                    this.CodigoField = value;
                    this.RaisePropertyChanged("Codigo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPadre {
            get {
                return this.IdPadreField;
            }
            set {
                if ((this.IdPadreField.Equals(value) != true)) {
                    this.IdPadreField = value;
                    this.RaisePropertyChanged("IdPadre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdTipo {
            get {
                return this.IdTipoField;
            }
            set {
                if ((this.IdTipoField.Equals(value) != true)) {
                    this.IdTipoField = value;
                    this.RaisePropertyChanged("IdTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUbicacionGeografica {
            get {
                return this.IdUbicacionGeograficaField;
            }
            set {
                if ((this.IdUbicacionGeograficaField.Equals(value) != true)) {
                    this.IdUbicacionGeograficaField = value;
                    this.RaisePropertyChanged("IdUbicacionGeografica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1 Padre {
            get {
                return this.PadreField;
            }
            set {
                if ((object.ReferenceEquals(this.PadreField, value) != true)) {
                    this.PadreField = value;
                    this.RaisePropertyChanged("Padre");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato")]
    public interface IUbicacionGeograficaContrato {
        
        // CODEGEN: Generating message contract since element name DameListadoPorPadreResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionGeograficaContrato/DameListadoPorPadre", ReplyAction="http://tempuri.org/IUbicacionGeograficaContrato/DameListadoPorPadreResponse")]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreResponse DameListadoPorPadre(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequest request);
        
        // CODEGEN: Generating message contract since element name DameUbicacionGeograficaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionGeograficaContrato/DameUbicacionGeografica", ReplyAction="http://tempuri.org/IUbicacionGeograficaContrato/DameUbicacionGeograficaResponse")]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaResponse DameUbicacionGeografica(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequest request);
        
        // CODEGEN: Generating message contract since element name nombreUbicacionDistribuidora from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionGeograficaContrato/BuscarUbicacionPorNombre", ReplyAction="http://tempuri.org/IUbicacionGeograficaContrato/BuscarUbicacionPorNombreResponse")]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreResponse BuscarUbicacionPorNombre(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionGeograficaContrato/DameUbicacionGeograficaPadrePorTi" +
            "po", ReplyAction="http://tempuri.org/IUbicacionGeograficaContrato/DameUbicacionGeograficaPadrePorTi" +
            "poResponse")]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1 DameUbicacionGeograficaPadrePorTipo(int idUbicacionGeografica, short idUbicacionGeograficaTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionGeograficaContrato/ObtenerUGTodas", ReplyAction="http://tempuri.org/IUbicacionGeograficaContrato/ObtenerUGTodasResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1> ObtenerUGTodas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUbicacionGeograficaContrato/ObtenerUGActivoTodas", ReplyAction="http://tempuri.org/IUbicacionGeograficaContrato/ObtenerUGActivoTodasResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1> ObtenerUGActivoTodas();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DameListadoPorPadreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DameListadoPorPadre", Namespace="http://tempuri.org/", Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequestBody Body;
        
        public DameListadoPorPadreRequest() {
        }
        
        public DameListadoPorPadreRequest(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DameListadoPorPadreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPadre;
        
        public DameListadoPorPadreRequestBody() {
        }
        
        public DameListadoPorPadreRequestBody(int idPadre) {
            this.idPadre = idPadre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DameListadoPorPadreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DameListadoPorPadreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreResponseBody Body;
        
        public DameListadoPorPadreResponse() {
        }
        
        public DameListadoPorPadreResponse(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DameListadoPorPadreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica> DameListadoPorPadreResult;
        
        public DameListadoPorPadreResponseBody() {
        }
        
        public DameListadoPorPadreResponseBody(System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica> DameListadoPorPadreResult) {
            this.DameListadoPorPadreResult = DameListadoPorPadreResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DameUbicacionGeograficaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DameUbicacionGeografica", Namespace="http://tempuri.org/", Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequestBody Body;
        
        public DameUbicacionGeograficaRequest() {
        }
        
        public DameUbicacionGeograficaRequest(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DameUbicacionGeograficaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idUbicacionGeografica;
        
        public DameUbicacionGeograficaRequestBody() {
        }
        
        public DameUbicacionGeograficaRequestBody(int idUbicacionGeografica) {
            this.idUbicacionGeografica = idUbicacionGeografica;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DameUbicacionGeograficaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DameUbicacionGeograficaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaResponseBody Body;
        
        public DameUbicacionGeograficaResponse() {
        }
        
        public DameUbicacionGeograficaResponse(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DameUbicacionGeograficaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica DameUbicacionGeograficaResult;
        
        public DameUbicacionGeograficaResponseBody() {
        }
        
        public DameUbicacionGeograficaResponseBody(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica DameUbicacionGeograficaResult) {
            this.DameUbicacionGeograficaResult = DameUbicacionGeograficaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUbicacionPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUbicacionPorNombre", Namespace="http://tempuri.org/", Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequestBody Body;
        
        public BuscarUbicacionPorNombreRequest() {
        }
        
        public BuscarUbicacionPorNombreRequest(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUbicacionPorNombreRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreUbicacionDistribuidora;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int idTipo;
        
        public BuscarUbicacionPorNombreRequestBody() {
        }
        
        public BuscarUbicacionPorNombreRequestBody(string nombreUbicacionDistribuidora, int idTipo) {
            this.nombreUbicacionDistribuidora = nombreUbicacionDistribuidora;
            this.idTipo = idTipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BuscarUbicacionPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BuscarUbicacionPorNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreResponseBody Body;
        
        public BuscarUbicacionPorNombreResponse() {
        }
        
        public BuscarUbicacionPorNombreResponse(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarUbicacionPorNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica BuscarUbicacionPorNombreResult;
        
        public BuscarUbicacionPorNombreResponseBody() {
        }
        
        public BuscarUbicacionPorNombreResponseBody(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica BuscarUbicacionPorNombreResult) {
            this.BuscarUbicacionPorNombreResult = BuscarUbicacionPorNombreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IUbicacionGeograficaContratoChannel : Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UbicacionGeograficaContratoClient : System.ServiceModel.ClientBase<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato>, Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato {
        
        public UbicacionGeograficaContratoClient() {
        }
        
        public UbicacionGeograficaContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UbicacionGeograficaContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UbicacionGeograficaContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UbicacionGeograficaContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreResponse Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato.DameListadoPorPadre(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequest request) {
            return base.Channel.DameListadoPorPadre(request);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica> DameListadoPorPadre(int idPadre) {
            Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequest inValue = new Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequest();
            inValue.Body = new Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreRequestBody();
            inValue.Body.idPadre = idPadre;
            Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameListadoPorPadreResponse retVal = ((Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato)(this)).DameListadoPorPadre(inValue);
            return retVal.Body.DameListadoPorPadreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaResponse Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato.DameUbicacionGeografica(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequest request) {
            return base.Channel.DameUbicacionGeografica(request);
        }
        
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica DameUbicacionGeografica(int idUbicacionGeografica) {
            Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequest inValue = new Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequest();
            inValue.Body = new Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaRequestBody();
            inValue.Body.idUbicacionGeografica = idUbicacionGeografica;
            Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.DameUbicacionGeograficaResponse retVal = ((Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato)(this)).DameUbicacionGeografica(inValue);
            return retVal.Body.DameUbicacionGeograficaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreResponse Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato.BuscarUbicacionPorNombre(Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequest request) {
            return base.Channel.BuscarUbicacionPorNombre(request);
        }
        
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica BuscarUbicacionPorNombre(string nombreUbicacionDistribuidora, int idTipo) {
            Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequest inValue = new Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequest();
            inValue.Body = new Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreRequestBody();
            inValue.Body.nombreUbicacionDistribuidora = nombreUbicacionDistribuidora;
            inValue.Body.idTipo = idTipo;
            Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.BuscarUbicacionPorNombreResponse retVal = ((Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.IUbicacionGeograficaContrato)(this)).BuscarUbicacionPorNombre(inValue);
            return retVal.Body.BuscarUbicacionPorNombreResult;
        }
        
        public Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1 DameUbicacionGeograficaPadrePorTipo(int idUbicacionGeografica, short idUbicacionGeograficaTipo) {
            return base.Channel.DameUbicacionGeograficaPadrePorTipo(idUbicacionGeografica, idUbicacionGeograficaTipo);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1> ObtenerUGTodas() {
            return base.Channel.ObtenerUGTodas();
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.UbicacionGeograficaServicio_T.UbicacionGeografica1> ObtenerUGActivoTodas() {
            return base.Channel.ObtenerUGActivoTodas();
        }
    }
}
