//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ine.SihPublico.UI.Web.VentaServicio_T {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Venta", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Venta.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Venta : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgenteEconomicoAgenteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdMonedaTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.VentaDetalle> VentaDetallesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenteEconomicoAgenteTipo {
            get {
                return this.IdAgenteEconomicoAgenteTipoField;
            }
            set {
                if ((this.IdAgenteEconomicoAgenteTipoField.Equals(value) != true)) {
                    this.IdAgenteEconomicoAgenteTipoField = value;
                    this.RaisePropertyChanged("IdAgenteEconomicoAgenteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdMonedaTipo {
            get {
                return this.IdMonedaTipoField;
            }
            set {
                if ((this.IdMonedaTipoField.Equals(value) != true)) {
                    this.IdMonedaTipoField = value;
                    this.RaisePropertyChanged("IdMonedaTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((this.IdVentaField.Equals(value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.VentaDetalle> VentaDetalles {
            get {
                return this.VentaDetallesField;
            }
            set {
                if ((object.ReferenceEquals(this.VentaDetallesField, value) != true)) {
                    this.VentaDetallesField = value;
                    this.RaisePropertyChanged("VentaDetalles");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VentaDetalle", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Venta.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class VentaDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoxPresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdVentaDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal PrecioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.VentaServicio_T.Venta VentaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal VolumenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductoxPresentacion {
            get {
                return this.IdProductoxPresentacionField;
            }
            set {
                if ((this.IdProductoxPresentacionField.Equals(value) != true)) {
                    this.IdProductoxPresentacionField = value;
                    this.RaisePropertyChanged("IdProductoxPresentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVenta {
            get {
                return this.IdVentaField;
            }
            set {
                if ((this.IdVentaField.Equals(value) != true)) {
                    this.IdVentaField = value;
                    this.RaisePropertyChanged("IdVenta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVentaDetalle {
            get {
                return this.IdVentaDetalleField;
            }
            set {
                if ((this.IdVentaDetalleField.Equals(value) != true)) {
                    this.IdVentaDetalleField = value;
                    this.RaisePropertyChanged("IdVentaDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio {
            get {
                return this.PrecioField;
            }
            set {
                if ((this.PrecioField.Equals(value) != true)) {
                    this.PrecioField = value;
                    this.RaisePropertyChanged("Precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ine.SihPublico.UI.Web.VentaServicio_T.Venta Venta {
            get {
                return this.VentaField;
            }
            set {
                if ((object.ReferenceEquals(this.VentaField, value) != true)) {
                    this.VentaField = value;
                    this.RaisePropertyChanged("Venta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Volumen {
            get {
                return this.VolumenField;
            }
            set {
                if ((this.VolumenField.Equals(value) != true)) {
                    this.VolumenField = value;
                    this.RaisePropertyChanged("Volumen");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="VentaServicio_T.IVentaContrato")]
    public interface IVentaContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaContrato/Obtener", ReplyAction="http://tempuri.org/IVentaContrato/ObtenerResponse")]
        Ine.SihPublico.UI.Web.VentaServicio_T.Venta Obtener(int idVenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaContrato/ObtenerListadoPorFecha", ReplyAction="http://tempuri.org/IVentaContrato/ObtenerListadoPorFechaResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.Venta> ObtenerListadoPorFecha(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaContrato/ObtenerListadoPorFechaActivo", ReplyAction="http://tempuri.org/IVentaContrato/ObtenerListadoPorFechaActivoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.Venta> ObtenerListadoPorFechaActivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaContrato/ObtenerListadoPorFechaInactivo", ReplyAction="http://tempuri.org/IVentaContrato/ObtenerListadoPorFechaInactivoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.Venta> ObtenerListadoPorFechaInactivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaContrato/Guardar", ReplyAction="http://tempuri.org/IVentaContrato/GuardarResponse")]
        bool Guardar(Ine.SihPublico.UI.Web.VentaServicio_T.Venta venta, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IVentaContrato/VerificarVenta", ReplyAction="http://tempuri.org/IVentaContrato/VerificarVentaResponse")]
        bool VerificarVenta(Ine.SihPublico.UI.Web.VentaServicio_T.Venta venta);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVentaContratoChannel : Ine.SihPublico.UI.Web.VentaServicio_T.IVentaContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VentaContratoClient : System.ServiceModel.ClientBase<Ine.SihPublico.UI.Web.VentaServicio_T.IVentaContrato>, Ine.SihPublico.UI.Web.VentaServicio_T.IVentaContrato {
        
        public VentaContratoClient() {
        }
        
        public VentaContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VentaContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VentaContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ine.SihPublico.UI.Web.VentaServicio_T.Venta Obtener(int idVenta) {
            return base.Channel.Obtener(idVenta);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.Venta> ObtenerListadoPorFecha(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ObtenerListadoPorFecha(idAgenteEconomicoAgenteTipo, fechaInicio, fechaFin);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.Venta> ObtenerListadoPorFechaActivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ObtenerListadoPorFechaActivo(idAgenteEconomicoAgenteTipo, fechaInicio, fechaFin);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.VentaServicio_T.Venta> ObtenerListadoPorFechaInactivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin) {
            return base.Channel.ObtenerListadoPorFechaInactivo(idAgenteEconomicoAgenteTipo, fechaInicio, fechaFin);
        }
        
        public bool Guardar(Ine.SihPublico.UI.Web.VentaServicio_T.Venta venta, int idUsuario) {
            return base.Channel.Guardar(venta, idUsuario);
        }
        
        public bool VerificarVenta(Ine.SihPublico.UI.Web.VentaServicio_T.Venta venta) {
            return base.Channel.VerificarVenta(venta);
        }
    }
}
