//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ine.SihPublico.UI.Web.ProductoServicio_T {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Producto", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Producto.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Producto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.CapacidadAlmacenamiento> CapacidadesAlmacenamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdProductoTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreComercialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreGenericoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.ProductoPresentacionTipo> ProductoPresentacionTiposField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.CapacidadAlmacenamiento> CapacidadesAlmacenamiento {
            get {
                return this.CapacidadesAlmacenamientoField;
            }
            set {
                if ((object.ReferenceEquals(this.CapacidadesAlmacenamientoField, value) != true)) {
                    this.CapacidadesAlmacenamientoField = value;
                    this.RaisePropertyChanged("CapacidadesAlmacenamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionProducto {
            get {
                return this.DescripcionProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionProductoField, value) != true)) {
                    this.DescripcionProductoField = value;
                    this.RaisePropertyChanged("DescripcionProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdProductoTipo {
            get {
                return this.IdProductoTipoField;
            }
            set {
                if ((this.IdProductoTipoField.Equals(value) != true)) {
                    this.IdProductoTipoField = value;
                    this.RaisePropertyChanged("IdProductoTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreComercial {
            get {
                return this.NombreComercialField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreComercialField, value) != true)) {
                    this.NombreComercialField = value;
                    this.RaisePropertyChanged("NombreComercial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreGenerico {
            get {
                return this.NombreGenericoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreGenericoField, value) != true)) {
                    this.NombreGenericoField = value;
                    this.RaisePropertyChanged("NombreGenerico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.ProductoPresentacionTipo> ProductoPresentacionTipos {
            get {
                return this.ProductoPresentacionTiposField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoPresentacionTiposField, value) != true)) {
                    this.ProductoPresentacionTiposField = value;
                    this.RaisePropertyChanged("ProductoPresentacionTipos");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CapacidadAlmacenamiento", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Producto.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class CapacidadAlmacenamiento : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> AnosVidaUtilTanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CapacidadAlmacenamientoTanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> DiametroTuberiaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaCierreTanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInstalacionTanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgenteEconomicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdCapacidadAlmacenamientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> IdTanqueInstalacionTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> IdTanqueTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> IdTuberiaMarcaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> IdTuberiaMaterialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> IdTuberiaTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdentificacionTanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedidasTanqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.ProductoServicio_T.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> AnosVidaUtilTanque {
            get {
                return this.AnosVidaUtilTanqueField;
            }
            set {
                if ((this.AnosVidaUtilTanqueField.Equals(value) != true)) {
                    this.AnosVidaUtilTanqueField = value;
                    this.RaisePropertyChanged("AnosVidaUtilTanque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CapacidadAlmacenamientoTanque {
            get {
                return this.CapacidadAlmacenamientoTanqueField;
            }
            set {
                if ((this.CapacidadAlmacenamientoTanqueField.Equals(value) != true)) {
                    this.CapacidadAlmacenamientoTanqueField = value;
                    this.RaisePropertyChanged("CapacidadAlmacenamientoTanque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> DiametroTuberia {
            get {
                return this.DiametroTuberiaField;
            }
            set {
                if ((this.DiametroTuberiaField.Equals(value) != true)) {
                    this.DiametroTuberiaField = value;
                    this.RaisePropertyChanged("DiametroTuberia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaCierreTanque {
            get {
                return this.FechaCierreTanqueField;
            }
            set {
                if ((this.FechaCierreTanqueField.Equals(value) != true)) {
                    this.FechaCierreTanqueField = value;
                    this.RaisePropertyChanged("FechaCierreTanque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInstalacionTanque {
            get {
                return this.FechaInstalacionTanqueField;
            }
            set {
                if ((this.FechaInstalacionTanqueField.Equals(value) != true)) {
                    this.FechaInstalacionTanqueField = value;
                    this.RaisePropertyChanged("FechaInstalacionTanque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenteEconomico {
            get {
                return this.IdAgenteEconomicoField;
            }
            set {
                if ((this.IdAgenteEconomicoField.Equals(value) != true)) {
                    this.IdAgenteEconomicoField = value;
                    this.RaisePropertyChanged("IdAgenteEconomico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCapacidadAlmacenamiento {
            get {
                return this.IdCapacidadAlmacenamientoField;
            }
            set {
                if ((this.IdCapacidadAlmacenamientoField.Equals(value) != true)) {
                    this.IdCapacidadAlmacenamientoField = value;
                    this.RaisePropertyChanged("IdCapacidadAlmacenamiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> IdTanqueInstalacionTipo {
            get {
                return this.IdTanqueInstalacionTipoField;
            }
            set {
                if ((this.IdTanqueInstalacionTipoField.Equals(value) != true)) {
                    this.IdTanqueInstalacionTipoField = value;
                    this.RaisePropertyChanged("IdTanqueInstalacionTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> IdTanqueTipo {
            get {
                return this.IdTanqueTipoField;
            }
            set {
                if ((this.IdTanqueTipoField.Equals(value) != true)) {
                    this.IdTanqueTipoField = value;
                    this.RaisePropertyChanged("IdTanqueTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> IdTuberiaMarca {
            get {
                return this.IdTuberiaMarcaField;
            }
            set {
                if ((this.IdTuberiaMarcaField.Equals(value) != true)) {
                    this.IdTuberiaMarcaField = value;
                    this.RaisePropertyChanged("IdTuberiaMarca");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> IdTuberiaMaterial {
            get {
                return this.IdTuberiaMaterialField;
            }
            set {
                if ((this.IdTuberiaMaterialField.Equals(value) != true)) {
                    this.IdTuberiaMaterialField = value;
                    this.RaisePropertyChanged("IdTuberiaMaterial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> IdTuberiaTipo {
            get {
                return this.IdTuberiaTipoField;
            }
            set {
                if ((this.IdTuberiaTipoField.Equals(value) != true)) {
                    this.IdTuberiaTipoField = value;
                    this.RaisePropertyChanged("IdTuberiaTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionTanque {
            get {
                return this.IdentificacionTanqueField;
            }
            set {
                if ((object.ReferenceEquals(this.IdentificacionTanqueField, value) != true)) {
                    this.IdentificacionTanqueField = value;
                    this.RaisePropertyChanged("IdentificacionTanque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedidasTanque {
            get {
                return this.MedidasTanqueField;
            }
            set {
                if ((object.ReferenceEquals(this.MedidasTanqueField, value) != true)) {
                    this.MedidasTanqueField = value;
                    this.RaisePropertyChanged("MedidasTanque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ine.SihPublico.UI.Web.ProductoServicio_T.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductoPresentacionTipo", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Producto.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class ProductoPresentacionTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AplicaISCField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AplicaIVAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoAdicionalDetallistaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoAdicionalMayoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CostoAdicionalMinoristaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FactorConversionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdPresentacionTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoxPresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OrdenField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.ProductoServicio_T.Producto ProductoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AplicaISC {
            get {
                return this.AplicaISCField;
            }
            set {
                if ((this.AplicaISCField.Equals(value) != true)) {
                    this.AplicaISCField = value;
                    this.RaisePropertyChanged("AplicaISC");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AplicaIVA {
            get {
                return this.AplicaIVAField;
            }
            set {
                if ((this.AplicaIVAField.Equals(value) != true)) {
                    this.AplicaIVAField = value;
                    this.RaisePropertyChanged("AplicaIVA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoAdicionalDetallista {
            get {
                return this.CostoAdicionalDetallistaField;
            }
            set {
                if ((this.CostoAdicionalDetallistaField.Equals(value) != true)) {
                    this.CostoAdicionalDetallistaField = value;
                    this.RaisePropertyChanged("CostoAdicionalDetallista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoAdicionalMayorista {
            get {
                return this.CostoAdicionalMayoristaField;
            }
            set {
                if ((this.CostoAdicionalMayoristaField.Equals(value) != true)) {
                    this.CostoAdicionalMayoristaField = value;
                    this.RaisePropertyChanged("CostoAdicionalMayorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CostoAdicionalMinorista {
            get {
                return this.CostoAdicionalMinoristaField;
            }
            set {
                if ((this.CostoAdicionalMinoristaField.Equals(value) != true)) {
                    this.CostoAdicionalMinoristaField = value;
                    this.RaisePropertyChanged("CostoAdicionalMinorista");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FactorConversion {
            get {
                return this.FactorConversionField;
            }
            set {
                if ((this.FactorConversionField.Equals(value) != true)) {
                    this.FactorConversionField = value;
                    this.RaisePropertyChanged("FactorConversion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdPresentacionTipo {
            get {
                return this.IdPresentacionTipoField;
            }
            set {
                if ((this.IdPresentacionTipoField.Equals(value) != true)) {
                    this.IdPresentacionTipoField = value;
                    this.RaisePropertyChanged("IdPresentacionTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProducto {
            get {
                return this.IdProductoField;
            }
            set {
                if ((this.IdProductoField.Equals(value) != true)) {
                    this.IdProductoField = value;
                    this.RaisePropertyChanged("IdProducto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductoxPresentacion {
            get {
                return this.IdProductoxPresentacionField;
            }
            set {
                if ((this.IdProductoxPresentacionField.Equals(value) != true)) {
                    this.IdProductoxPresentacionField = value;
                    this.RaisePropertyChanged("IdProductoxPresentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Orden {
            get {
                return this.OrdenField;
            }
            set {
                if ((this.OrdenField.Equals(value) != true)) {
                    this.OrdenField = value;
                    this.RaisePropertyChanged("Orden");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ine.SihPublico.UI.Web.ProductoServicio_T.Producto Producto {
            get {
                return this.ProductoField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductoField, value) != true)) {
                    this.ProductoField = value;
                    this.RaisePropertyChanged("Producto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProductoServicio_T.IProductoContrato")]
    public interface IProductoContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoContrato/Obtener", ReplyAction="http://tempuri.org/IProductoContrato/ObtenerResponse")]
        Ine.SihPublico.UI.Web.ProductoServicio_T.Producto Obtener(int idProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoContrato/ObtenerListadoPorAgenteEconomico", ReplyAction="http://tempuri.org/IProductoContrato/ObtenerListadoPorAgenteEconomicoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.Producto> ObtenerListadoPorAgenteEconomico(int idAgenteEconomico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoContrato/ObtenerListadoPorAgenteEconomicoActivo", ReplyAction="http://tempuri.org/IProductoContrato/ObtenerListadoPorAgenteEconomicoActivoRespon" +
            "se")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.Producto> ObtenerListadoPorAgenteEconomicoActivo(int idAgenteEconomico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IProductoContrato/ObtenerListadoPorAgenteEconomicoInactivo", ReplyAction="http://tempuri.org/IProductoContrato/ObtenerListadoPorAgenteEconomicoInactivoResp" +
            "onse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.Producto> ObtenerListadoPorAgenteEconomicoInactivo(int idAgenteEconomico);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IProductoContratoChannel : Ine.SihPublico.UI.Web.ProductoServicio_T.IProductoContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoContratoClient : System.ServiceModel.ClientBase<Ine.SihPublico.UI.Web.ProductoServicio_T.IProductoContrato>, Ine.SihPublico.UI.Web.ProductoServicio_T.IProductoContrato {
        
        public ProductoContratoClient() {
        }
        
        public ProductoContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ine.SihPublico.UI.Web.ProductoServicio_T.Producto Obtener(int idProducto) {
            return base.Channel.Obtener(idProducto);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.Producto> ObtenerListadoPorAgenteEconomico(int idAgenteEconomico) {
            return base.Channel.ObtenerListadoPorAgenteEconomico(idAgenteEconomico);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.Producto> ObtenerListadoPorAgenteEconomicoActivo(int idAgenteEconomico) {
            return base.Channel.ObtenerListadoPorAgenteEconomicoActivo(idAgenteEconomico);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.ProductoServicio_T.Producto> ObtenerListadoPorAgenteEconomicoInactivo(int idAgenteEconomico) {
            return base.Channel.ObtenerListadoPorAgenteEconomicoInactivo(idAgenteEconomico);
        }
    }
}
