//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgenteEconomico", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.AgenteEconomico.Contrato" +
        "", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AgenteEconomico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdministradorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomicoAgenteTipo> AgenteEconomicoAgenteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApartadoPostalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CelularField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DireccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ElevacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FaxField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaInicioOperacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgenteEconomicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdBandaUTMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdPersonaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdZonaUTMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreAgenteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PrecisionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelefonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UtmEsteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> UtmNorteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Administrador {
            get {
                return this.AdministradorField;
            }
            set {
                if ((object.ReferenceEquals(this.AdministradorField, value) != true)) {
                    this.AdministradorField = value;
                    this.RaisePropertyChanged("Administrador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomicoAgenteTipo> AgenteEconomicoAgenteTipo {
            get {
                return this.AgenteEconomicoAgenteTipoField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenteEconomicoAgenteTipoField, value) != true)) {
                    this.AgenteEconomicoAgenteTipoField = value;
                    this.RaisePropertyChanged("AgenteEconomicoAgenteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApartadoPostal {
            get {
                return this.ApartadoPostalField;
            }
            set {
                if ((object.ReferenceEquals(this.ApartadoPostalField, value) != true)) {
                    this.ApartadoPostalField = value;
                    this.RaisePropertyChanged("ApartadoPostal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Celular {
            get {
                return this.CelularField;
            }
            set {
                if ((object.ReferenceEquals(this.CelularField, value) != true)) {
                    this.CelularField = value;
                    this.RaisePropertyChanged("Celular");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion {
            get {
                return this.DireccionField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionField, value) != true)) {
                    this.DireccionField = value;
                    this.RaisePropertyChanged("Direccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Elevacion {
            get {
                return this.ElevacionField;
            }
            set {
                if ((this.ElevacionField.Equals(value) != true)) {
                    this.ElevacionField = value;
                    this.RaisePropertyChanged("Elevacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fax {
            get {
                return this.FaxField;
            }
            set {
                if ((object.ReferenceEquals(this.FaxField, value) != true)) {
                    this.FaxField = value;
                    this.RaisePropertyChanged("Fax");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaInicioOperacion {
            get {
                return this.FechaInicioOperacionField;
            }
            set {
                if ((this.FechaInicioOperacionField.Equals(value) != true)) {
                    this.FechaInicioOperacionField = value;
                    this.RaisePropertyChanged("FechaInicioOperacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenteEconomico {
            get {
                return this.IdAgenteEconomicoField;
            }
            set {
                if ((this.IdAgenteEconomicoField.Equals(value) != true)) {
                    this.IdAgenteEconomicoField = value;
                    this.RaisePropertyChanged("IdAgenteEconomico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdBandaUTM {
            get {
                return this.IdBandaUTMField;
            }
            set {
                if ((this.IdBandaUTMField.Equals(value) != true)) {
                    this.IdBandaUTMField = value;
                    this.RaisePropertyChanged("IdBandaUTM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPersona {
            get {
                return this.IdPersonaField;
            }
            set {
                if ((this.IdPersonaField.Equals(value) != true)) {
                    this.IdPersonaField = value;
                    this.RaisePropertyChanged("IdPersona");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUbicacion {
            get {
                return this.IdUbicacionField;
            }
            set {
                if ((this.IdUbicacionField.Equals(value) != true)) {
                    this.IdUbicacionField = value;
                    this.RaisePropertyChanged("IdUbicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdZonaUTM {
            get {
                return this.IdZonaUTMField;
            }
            set {
                if ((this.IdZonaUTMField.Equals(value) != true)) {
                    this.IdZonaUTMField = value;
                    this.RaisePropertyChanged("IdZonaUTM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAgente {
            get {
                return this.NombreAgenteField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreAgenteField, value) != true)) {
                    this.NombreAgenteField = value;
                    this.RaisePropertyChanged("NombreAgente");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Precision {
            get {
                return this.PrecisionField;
            }
            set {
                if ((this.PrecisionField.Equals(value) != true)) {
                    this.PrecisionField = value;
                    this.RaisePropertyChanged("Precision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono {
            get {
                return this.TelefonoField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonoField, value) != true)) {
                    this.TelefonoField = value;
                    this.RaisePropertyChanged("Telefono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UtmEste {
            get {
                return this.UtmEsteField;
            }
            set {
                if ((this.UtmEsteField.Equals(value) != true)) {
                    this.UtmEsteField = value;
                    this.RaisePropertyChanged("UtmEste");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> UtmNorte {
            get {
                return this.UtmNorteField;
            }
            set {
                if ((this.UtmNorteField.Equals(value) != true)) {
                    this.UtmNorteField = value;
                    this.RaisePropertyChanged("UtmNorte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Web {
            get {
                return this.WebField;
            }
            set {
                if ((object.ReferenceEquals(this.WebField, value) != true)) {
                    this.WebField = value;
                    this.RaisePropertyChanged("Web");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AgenteEconomicoAgenteTipo", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.AgenteEconomico.Contrato" +
        "", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class AgenteEconomicoAgenteTipo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico AgenteEconomicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgenteEconomicoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgenteEconomicoAgenteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdAgenteEstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdAgenteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short IdMarcaCompaniaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TieneLicenciaOperacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico AgenteEconomico {
            get {
                return this.AgenteEconomicoField;
            }
            set {
                if ((object.ReferenceEquals(this.AgenteEconomicoField, value) != true)) {
                    this.AgenteEconomicoField = value;
                    this.RaisePropertyChanged("AgenteEconomico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenteEconomico {
            get {
                return this.IdAgenteEconomicoField;
            }
            set {
                if ((this.IdAgenteEconomicoField.Equals(value) != true)) {
                    this.IdAgenteEconomicoField = value;
                    this.RaisePropertyChanged("IdAgenteEconomico");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenteEconomicoAgenteTipo {
            get {
                return this.IdAgenteEconomicoAgenteTipoField;
            }
            set {
                if ((this.IdAgenteEconomicoAgenteTipoField.Equals(value) != true)) {
                    this.IdAgenteEconomicoAgenteTipoField = value;
                    this.RaisePropertyChanged("IdAgenteEconomicoAgenteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdAgenteEstado {
            get {
                return this.IdAgenteEstadoField;
            }
            set {
                if ((this.IdAgenteEstadoField.Equals(value) != true)) {
                    this.IdAgenteEstadoField = value;
                    this.RaisePropertyChanged("IdAgenteEstado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdAgenteTipo {
            get {
                return this.IdAgenteTipoField;
            }
            set {
                if ((this.IdAgenteTipoField.Equals(value) != true)) {
                    this.IdAgenteTipoField = value;
                    this.RaisePropertyChanged("IdAgenteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short IdMarcaCompania {
            get {
                return this.IdMarcaCompaniaField;
            }
            set {
                if ((this.IdMarcaCompaniaField.Equals(value) != true)) {
                    this.IdMarcaCompaniaField = value;
                    this.RaisePropertyChanged("IdMarcaCompania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TieneLicenciaOperacion {
            get {
                return this.TieneLicenciaOperacionField;
            }
            set {
                if ((this.TieneLicenciaOperacionField.Equals(value) != true)) {
                    this.TieneLicenciaOperacionField = value;
                    this.RaisePropertyChanged("TieneLicenciaOperacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AgenteEconomicoServicio_T.IAgenteEconomicoContrato")]
    public interface IAgenteEconomicoContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/Obtener", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerResponse")]
        Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico Obtener(int idAgenteEconomico);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerPorPersona", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerPorPersonaResponse")]
        Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico ObtenerPorPersona(int idPersona);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListado", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListado();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoActivos", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoActivosResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoActivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoInactivos", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoInactivosResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoInactivos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoPorIdAgenteEconomico", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoPorIdAgenteEconomicoRes" +
            "ponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoPorIdAgenteEconomico(System.Collections.Generic.List<int> listadoId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerAgenteEconomicoAgenteTipo", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerAgenteEconomicoAgenteTipoRespo" +
            "nse")]
        Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomicoAgenteTipo ObtenerAgenteEconomicoAgenteTipo(int idAgenteEconomico, int idAgenteTipo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerAgenteEconomicoInfo", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerAgenteEconomicoInfoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerAgenteEconomicoInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoPorIdAgenteEconomicoAge" +
            "nteTipo", ReplyAction="http://tempuri.org/IAgenteEconomicoContrato/ObtenerListadoPorIdAgenteEconomicoAge" +
            "nteTipoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoPorIdAgenteEconomicoAgenteTipo(System.Collections.Generic.List<int> listadoIds);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAgenteEconomicoContratoChannel : Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.IAgenteEconomicoContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AgenteEconomicoContratoClient : System.ServiceModel.ClientBase<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.IAgenteEconomicoContrato>, Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.IAgenteEconomicoContrato {
        
        public AgenteEconomicoContratoClient() {
        }
        
        public AgenteEconomicoContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AgenteEconomicoContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenteEconomicoContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AgenteEconomicoContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico Obtener(int idAgenteEconomico) {
            return base.Channel.Obtener(idAgenteEconomico);
        }
        
        public Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico ObtenerPorPersona(int idPersona) {
            return base.Channel.ObtenerPorPersona(idPersona);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListado() {
            return base.Channel.ObtenerListado();
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoActivos() {
            return base.Channel.ObtenerListadoActivos();
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoInactivos() {
            return base.Channel.ObtenerListadoInactivos();
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoPorIdAgenteEconomico(System.Collections.Generic.List<int> listadoId) {
            return base.Channel.ObtenerListadoPorIdAgenteEconomico(listadoId);
        }
        
        public Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomicoAgenteTipo ObtenerAgenteEconomicoAgenteTipo(int idAgenteEconomico, int idAgenteTipo) {
            return base.Channel.ObtenerAgenteEconomicoAgenteTipo(idAgenteEconomico, idAgenteTipo);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerAgenteEconomicoInfo() {
            return base.Channel.ObtenerAgenteEconomicoInfo();
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.AgenteEconomicoServicio_T.AgenteEconomico> ObtenerListadoPorIdAgenteEconomicoAgenteTipo(System.Collections.Generic.List<int> listadoIds) {
            return base.Channel.ObtenerListadoPorIdAgenteEconomicoAgenteTipo(listadoIds);
        }
    }
}
