//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.33440
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ine.SihPublico.UI.Web.InventarioServicio_T {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Inventario", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Inventario.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class Inventario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.TimeSpan HoraCorteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdAgenteEconomicoAgenteTipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.InventarioDetalle> InventarioDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.TimeSpan HoraCorte {
            get {
                return this.HoraCorteField;
            }
            set {
                if ((this.HoraCorteField.Equals(value) != true)) {
                    this.HoraCorteField = value;
                    this.RaisePropertyChanged("HoraCorte");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAgenteEconomicoAgenteTipo {
            get {
                return this.IdAgenteEconomicoAgenteTipoField;
            }
            set {
                if ((this.IdAgenteEconomicoAgenteTipoField.Equals(value) != true)) {
                    this.IdAgenteEconomicoAgenteTipoField = value;
                    this.RaisePropertyChanged("IdAgenteEconomicoAgenteTipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInventario {
            get {
                return this.IdInventarioField;
            }
            set {
                if ((this.IdInventarioField.Equals(value) != true)) {
                    this.IdInventarioField = value;
                    this.RaisePropertyChanged("IdInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.InventarioDetalle> InventarioDetalle {
            get {
                return this.InventarioDetalleField;
            }
            set {
                if ((object.ReferenceEquals(this.InventarioDetalleField, value) != true)) {
                    this.InventarioDetalleField = value;
                    this.RaisePropertyChanged("InventarioDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InventarioDetalle", Namespace="http://schemas.datacontract.org/2004/07/INE.ServiciosWeb.Inventario.Contrato", IsReference=true)]
    [System.SerializableAttribute()]
    public partial class InventarioDetalle : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal CapacidadInstaladaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FechaModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> FondoNoOperativoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdInventarioDetalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdProductoxPresentacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> IdUsuarioModificacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdUsuarioRegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario InventarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal InventarioTotalField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TransferenciasField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal CapacidadInstalada {
            get {
                return this.CapacidadInstaladaField;
            }
            set {
                if ((this.CapacidadInstaladaField.Equals(value) != true)) {
                    this.CapacidadInstaladaField = value;
                    this.RaisePropertyChanged("CapacidadInstalada");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FechaModificacion {
            get {
                return this.FechaModificacionField;
            }
            set {
                if ((this.FechaModificacionField.Equals(value) != true)) {
                    this.FechaModificacionField = value;
                    this.RaisePropertyChanged("FechaModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRegistro {
            get {
                return this.FechaRegistroField;
            }
            set {
                if ((this.FechaRegistroField.Equals(value) != true)) {
                    this.FechaRegistroField = value;
                    this.RaisePropertyChanged("FechaRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> FondoNoOperativo {
            get {
                return this.FondoNoOperativoField;
            }
            set {
                if ((this.FondoNoOperativoField.Equals(value) != true)) {
                    this.FondoNoOperativoField = value;
                    this.RaisePropertyChanged("FondoNoOperativo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInventario {
            get {
                return this.IdInventarioField;
            }
            set {
                if ((this.IdInventarioField.Equals(value) != true)) {
                    this.IdInventarioField = value;
                    this.RaisePropertyChanged("IdInventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdInventarioDetalle {
            get {
                return this.IdInventarioDetalleField;
            }
            set {
                if ((this.IdInventarioDetalleField.Equals(value) != true)) {
                    this.IdInventarioDetalleField = value;
                    this.RaisePropertyChanged("IdInventarioDetalle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdProductoxPresentacion {
            get {
                return this.IdProductoxPresentacionField;
            }
            set {
                if ((this.IdProductoxPresentacionField.Equals(value) != true)) {
                    this.IdProductoxPresentacionField = value;
                    this.RaisePropertyChanged("IdProductoxPresentacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdUsuarioModificacion {
            get {
                return this.IdUsuarioModificacionField;
            }
            set {
                if ((this.IdUsuarioModificacionField.Equals(value) != true)) {
                    this.IdUsuarioModificacionField = value;
                    this.RaisePropertyChanged("IdUsuarioModificacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuarioRegistro {
            get {
                return this.IdUsuarioRegistroField;
            }
            set {
                if ((this.IdUsuarioRegistroField.Equals(value) != true)) {
                    this.IdUsuarioRegistroField = value;
                    this.RaisePropertyChanged("IdUsuarioRegistro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario Inventario {
            get {
                return this.InventarioField;
            }
            set {
                if ((object.ReferenceEquals(this.InventarioField, value) != true)) {
                    this.InventarioField = value;
                    this.RaisePropertyChanged("Inventario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InventarioTotal {
            get {
                return this.InventarioTotalField;
            }
            set {
                if ((this.InventarioTotalField.Equals(value) != true)) {
                    this.InventarioTotalField = value;
                    this.RaisePropertyChanged("InventarioTotal");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Transferencias {
            get {
                return this.TransferenciasField;
            }
            set {
                if ((this.TransferenciasField.Equals(value) != true)) {
                    this.TransferenciasField = value;
                    this.RaisePropertyChanged("Transferencias");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InventarioServicio_T.IInventarioContrato")]
    public interface IInventarioContrato {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/Obtener", ReplyAction="http://tempuri.org/IInventarioContrato/ObtenerResponse")]
        Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario Obtener(int idInventario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/ObtenerListadoPorFecha", ReplyAction="http://tempuri.org/IInventarioContrato/ObtenerListadoPorFechaResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario> ObtenerListadoPorFecha(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin, bool incluirFechasSinRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/ObtenerListadoPorFechaActivo", ReplyAction="http://tempuri.org/IInventarioContrato/ObtenerListadoPorFechaActivoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario> ObtenerListadoPorFechaActivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin, bool incluirFechasSinRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/ObtenerListadoPorFechaInactivo", ReplyAction="http://tempuri.org/IInventarioContrato/ObtenerListadoPorFechaInactivoResponse")]
        System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario> ObtenerListadoPorFechaInactivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin, bool incluirFechasSinRegistro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/Guardar", ReplyAction="http://tempuri.org/IInventarioContrato/GuardarResponse")]
        bool Guardar(Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario inventario, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/DarAlta", ReplyAction="http://tempuri.org/IInventarioContrato/DarAltaResponse")]
        bool DarAlta(int idInventario, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/DarBaja", ReplyAction="http://tempuri.org/IInventarioContrato/DarBajaResponse")]
        bool DarBaja(int idInventario, int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInventarioContrato/VerificarInventario", ReplyAction="http://tempuri.org/IInventarioContrato/VerificarInventarioResponse")]
        bool VerificarInventario(Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario inventario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IInventarioContratoChannel : Ine.SihPublico.UI.Web.InventarioServicio_T.IInventarioContrato, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InventarioContratoClient : System.ServiceModel.ClientBase<Ine.SihPublico.UI.Web.InventarioServicio_T.IInventarioContrato>, Ine.SihPublico.UI.Web.InventarioServicio_T.IInventarioContrato {
        
        public InventarioContratoClient() {
        }
        
        public InventarioContratoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InventarioContratoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventarioContratoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InventarioContratoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario Obtener(int idInventario) {
            return base.Channel.Obtener(idInventario);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario> ObtenerListadoPorFecha(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin, bool incluirFechasSinRegistro) {
            return base.Channel.ObtenerListadoPorFecha(idAgenteEconomicoAgenteTipo, fechaInicio, fechaFin, incluirFechasSinRegistro);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario> ObtenerListadoPorFechaActivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin, bool incluirFechasSinRegistro) {
            return base.Channel.ObtenerListadoPorFechaActivo(idAgenteEconomicoAgenteTipo, fechaInicio, fechaFin, incluirFechasSinRegistro);
        }
        
        public System.Collections.Generic.List<Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario> ObtenerListadoPorFechaInactivo(int idAgenteEconomicoAgenteTipo, System.DateTime fechaInicio, System.DateTime fechaFin, bool incluirFechasSinRegistro) {
            return base.Channel.ObtenerListadoPorFechaInactivo(idAgenteEconomicoAgenteTipo, fechaInicio, fechaFin, incluirFechasSinRegistro);
        }
        
        public bool Guardar(Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario inventario, int idUsuario) {
            return base.Channel.Guardar(inventario, idUsuario);
        }
        
        public bool DarAlta(int idInventario, int idUsuario) {
            return base.Channel.DarAlta(idInventario, idUsuario);
        }
        
        public bool DarBaja(int idInventario, int idUsuario) {
            return base.Channel.DarBaja(idInventario, idUsuario);
        }
        
        public bool VerificarInventario(Ine.SihPublico.UI.Web.InventarioServicio_T.Inventario inventario) {
            return base.Channel.VerificarInventario(inventario);
        }
    }
}
